---
root: true

extends:
  - airbnb
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
  - 'plugin:type-graphql/recommended'
  - 'prettier'
  - 'prettier/react'
  - 'prettier/@typescript-eslint'

parser: '@typescript-eslint/parser'

parserOptions:
  project: './tsconfig.json'

plugins:
  - '@typescript-eslint'
  - 'type-graphql'

env:
  browser: true
  node: true

rules:
  import/no-unresolved: 0
  import/extensions: 0
  react/prop-types: 0
